server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: warehouse

  data:
    mongodb:
      database: ${spring.application.name}
      uri: mongodb://localhost:27017
